### PR TITLE
feat: undo and reset button

### LINKED ISSUE #21: feat: Reset button and undo option
Hey ...
I want to work on this
Can u assign this to me?

### PR DESCRIPTION
**Pull request by Avinash-31**
Resolves #21

### CODE REVIEW

**Review by malivinayak — CHANGES_REQUESTED** [review]
https://github.com/malivinayak/Tic-Tac-Toe/assets/66154908/0a4b99e5-ba8b-4c79-8497-86f76e0e77f2

There is bug in undo logic as it is not undo the last player mover. 
Kindly address the same and fix it.

**Review by malivinayak — CHANGES_REQUESTED** [review]
Add hover feature for better understanding:
on hover it should display the button name. 
e.g. on hover on reset button it should display as Hover

**Comment by Avinash-31** [comment]
Okay i'll look into it

**Comment by malivinayak** [comment]
> Okay i'll look into it

You just need to add `title` tag and it will do the job

**Comment by malivinayak** [comment]
Or you can also implement this kind of style https://codepen.io/reeyhdz/pen/xLEexw

**Review by malivinayak — APPROVED** [review]

**Pull request merged**
