### PR TITLE
Added undo and reset button

### PR DESCRIPTION
**Pull request by Kedarnath-Rothe**
#Fixed issue #21 

https://github.com/malivinayak/Tic-Tac-Toe/assets/143418802/1e8ff70f-5f1f-48df-bcfd-1328120ad829

### CODE REVIEW

**Comment by Kedarnath-Rothe** [comment]
@malivinayak  Please ckeck my PR

**Review by malivinayak — CHANGES_REQUESTED** [review]
- [ ] button at left are not good as it is not accessible quickly.
- [ ] undo button is not working (it is good practice to open PR after all functionality)
- [ ] UI is not responsive 

 



| UI 1 | UI 2 |
|--------|--------|
| image | image |

**Comment by malivinayak** [comment]
@Avinash-31 is already working on same at #23 
I suggest you introduce a new feature with opening new issue

**Comment by malivinayak** [comment]
Closing PR as #23 accepted
- [x] #23

**Pull request closed without merging**
