### PR TITLE
ui update with few ui changes

### PR DESCRIPTION
**Pull request by Panth1823**
Before:
bef11
bef12

After:
aft11
aft12

### CODE REVIEW

**Comment by malivinayak** [comment]
| Current Version | Your Version |
| --- | --- |
| image | image |

 Checkout the difference, Rules are properly visible after game name heading but in your version name is not visible at all

What I liked:
- Hover is nice on game heading

Changes expected:
- Add same hover effect as above to result text
- Add proper padding to result text
- Keep roles button text font color as black as it is more visible than white

**Review by malivinayak — CHANGES_REQUESTED** [review]
Make changes addressed at https://github.com/malivinayak/Tic-Tac-Toe/pull/15#issuecomment-1747336608

**Comment by Panth1823** [comment]
Changes/Updates :
Add same hover effect as above to result text : Added
Add proper padding to result text : Added
Keep roles button text font color as black as it is more visible than white : Added


image
image
image
image

**Review by malivinayak — COMMENTED** [review]
getting branch conflicts as your branch is not updated with latest changes #7

**Comment by malivinayak** [comment]
you can contribute on different feature after pulling latest changes

**Pull request closed without merging**
