### PR TITLE
refactor: UI enhancement

### PR DESCRIPTION
**Pull request by taylorlottdixon**

### CODE REVIEW

**Review by malivinayak — CHANGES_REQUESTED** [review]
Can you update the linear-gradient combination as it is not visible properly.
Same with Result text

**Comment by malivinayak** [comment]
@taylorlottdixon this branch has conflicts due to #6 PR
You need to resolve the conflicts or create a new branch after updating the fork repo

**Comment by taylorlottdixon** [comment]
> Can you update the linear-gradient combination as it is not visible properly. Same with Result text

Do you mean the background of the div? I am seeing the gradient on the page background. I was making a suggestion to make the h1 backgrounds transparent for a cleaner look, but can certainly change it back if you prefer!

**Review by malivinayak — APPROVED** [review]
LGTM

**Pull request merged**
