### PR TITLE
feat: Tic-Tac-Toe Rules added as pop-up 

### LINKED ISSUE #3: Add "Rules" for Tic-Tac-Toe
Description:

The current version of the Tic-Tac-Toe game lacks information about the rules of the game, which is essential for players, especially those who might be new to the game. To improve the user experience and provide clarity on how the game is played, it is recommended to add a "Rules" button to the game interface.

Suggested Enhancement:

- Introduce a "Rules" button at the bottom of the game page.
- When users click on the "Rules" button, a popup should appear with detailed instructions explaining how to play Tic-Tac-Toe, including the rules, winning combinations, which player has which symbol, and how the game is typically conducted.

Expected Behavior:

Players will have easy access to the rules and instructions for the game by clicking the "Rules" button, which will display a popup with the necessary information.

### PR DESCRIPTION
**Pull request by Sankalp20Tiwari**
Resolves #3

### CODE REVIEW

**Review by malivinayak — CHANGES_REQUESTED** [review]
- Pop up button should be at bottom right
- After adding pop up button game  board must be at center vertically too as it was before
- The Result should be display below the board  
image

**Review by malivinayak — CHANGES_REQUESTED** [review]
Make Left Alignment to All 4 Rules and increase overall font size beat

**Comment by Sankalp20Tiwari** [comment]
Hey @malivinayak I have made the changes once again and made the commit. So i want you to take a look at the changes and merge the branch if everything is correct.

**Review by malivinayak — CHANGES_REQUESTED** [review]
As I already mentioned game board must be at center (vertically too) after adding the Rules button.

| Your Updated Version | Current Version |
| --- | --- |
| image | image |

You can clearly see the difference that in your updated version board is at upper side not at middle

**Comment by Sankalp20Tiwari** [comment]
@malivinayak I have made the required changes . Please check it once and tell me if I need to make any further changes.

**Comment by malivinayak** [comment]
> @malivinayak I have made the required changes . Please check it once and tell me if I need to make any further changes.

The same issue continued, I have fixed all the problems myself

**Comment by malivinayak** [comment]
| Your updated version | After my fixes |
| --- | --- |
| image | image |

**Review by malivinayak — APPROVED** [review]
Issues fixed by : 

@malivinayak
[style: margin height issue](https://github.com/malivinayak/Tic-Tac-Toe/pull/6/commits/49235c88a5e16fde64bd2591240a318b17824dac) 
[49235c8](https://github.com/malivinayak/Tic-Tac-Toe/pull/6/commits/49235c88a5e16fde64bd2591240a318b17824dac)
@malivinayak
[refactor: fix the button right and bottom margin](https://github.com/malivinayak/Tic-Tac-Toe/pull/6/commits/12f5c0a236524fd5d861aab1ce7baa348921d827) 
[12f5c0a](https://github.com/malivinayak/Tic-Tac-Toe/pull/6/commits/12f5c0a236524fd5d861aab1ce7baa348921d827)
@malivinayak
[refactor: Align playground vertically center](https://github.com/malivinayak/Tic-Tac-Toe/pull/6/commits/8931acb77d4cd8f9f219016a14b6b78f76d03b4d)
[8931acb](https://github.com/malivinayak/Tic-Tac-Toe/pull/6/commits/8931acb77d4cd8f9f219016a14b6b78f76d03b4d)
@malivinayak
[fix: result excess top margin](https://github.com/malivinayak/Tic-Tac-Toe/pull/6/commits/b41484fbb97ee2c27e80e3c232b791ee25265196)
[b41484f](https://github.com/malivinayak/Tic-Tac-Toe/pull/6/commits/b41484fbb97ee2c27e80e3c232b791ee25265196)
@malivinayak
[style: removing extra lines](https://github.com/malivinayak/Tic-Tac-Toe/pull/6/commits/8537623a397f4ce858139a8e9fe4d9c1179f322e)
[8537623](https://github.com/malivinayak/Tic-Tac-Toe/pull/6/commits/8537623a397f4ce858139a8e9fe4d9c1179f322e)

**Pull request merged**
